### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by ehsan2e** [dmanners/Manners_Widgets#1]
thanks for the great work but I have a problem with it I constantly get the following error in my browser console and nothing happens
Uncaught ReferenceError: options_fieldset66e0bd77a6251868e9e22f60624e3592_id_path5372c9737e67744732662ebcd473fd80_massactionJsObject is not defined

**Comment by dmanners** [comment]
Yes sorry, this is still a work in progress and does not currently work.

I will update this when I have some time.

**Comment by remklov** [comment]
Is there any progress? Tried to use it with adding multiple products, but i cannot fix the error.

**Comment by dmanners** [comment]
No sorry I have not been able to progress here, but thank you for reminding me.

**Comment by dmanners** [comment]
Hi @ehsan2e and @benevolk it might not be relevant for you now but I have extended the module so that it should now have no js error in the backend.
